image: ubuntu/lts
packages:
  - maven
  - openjdk-21-jre-headless
sources:
  - https://git.sr.ht/~taum/dedup
tasks:
  - dependencies: |
      cd lintstone
      mvn -B de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies
  - build_and_test: |
      cd lintstone
      mvn package -B